### ISSUE TITLE
Do you know how to record it as mp4 file?

### ISSUE THREAD

**Issue by HeroSony** [SwatiModi/portrait-segmentation-mediapipe#2]

**Comment by SwatiModi** [comment]
Hey @HeroSony, I don't know how to do that, although [this](https://github.com/google/mediapipe/issues/270) could help

**Comment by afsaredrisy** [comment]
It is bit late but if you are still looking for solution you can try following . 

https://github.com/afsaredrisy/MediapipeSegmentationGradle

**Comment by HeroSony** [comment]
Thanks, everyone.
